name: CI

on:
  push:
    branches:
      - main
      - develop

jobs:
  lint-format-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-versio: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run black
        run: |
          pip install black
          black . || true

      - name: Run pylint
        run: |
          pip install pylint
          pylint src || true

      - name: Run tests
        run: |
          pytest tests
